name: Trigger from Google Drive

on:
  repository_dispatch:
    types: [drive_upload]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mostrar detalles del archivo subido
        run: |
          echo "Nuevo archivo subido: ${{ github.event.client_payload.fileName }}"
          echo "ID del archivo: ${{ github.event.client_payload.fileId }}"